// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD849M3vB-OWEwQO_E2HI2NSylYDgxX8bs',
    appId: '1:637898546062:web:6bdbbea2adb791bb3ba2df',
    messagingSenderId: '637898546062',
    projectId: 'travela-ff3ef',
    authDomain: 'travela-ff3ef.firebaseapp.com',
    storageBucket: 'travela-ff3ef.firebasestorage.app',
    measurementId: 'G-H3NNSFRQ47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj35YrFyp-ZLs44mZbt-nHpxkdimPb9T0',
    appId: '1:637898546062:android:540d4ab2f0e5845e3ba2df',
    messagingSenderId: '637898546062',
    projectId: 'travela-ff3ef',
    storageBucket: 'travela-ff3ef.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSeDopclejm-BYeLLPC8nbVKvVevXGmwI',
    appId: '1:637898546062:ios:688342e5cbba01113ba2df',
    messagingSenderId: '637898546062',
    projectId: 'travela-ff3ef',
    storageBucket: 'travela-ff3ef.firebasestorage.app',
    iosBundleId: 'com.example.navigatorApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSeDopclejm-BYeLLPC8nbVKvVevXGmwI',
    appId: '1:637898546062:ios:688342e5cbba01113ba2df',
    messagingSenderId: '637898546062',
    projectId: 'travela-ff3ef',
    storageBucket: 'travela-ff3ef.firebasestorage.app',
    iosBundleId: 'com.example.navigatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD849M3vB-OWEwQO_E2HI2NSylYDgxX8bs',
    appId: '1:637898546062:web:f7ae86b21ad134a13ba2df',
    messagingSenderId: '637898546062',
    projectId: 'travela-ff3ef',
    authDomain: 'travela-ff3ef.firebaseapp.com',
    storageBucket: 'travela-ff3ef.firebasestorage.app',
    measurementId: 'G-E0YCV8DZWH',
  );
}
